import Head from "next/head";
import Image from "next/image";
import css from "../styles/Home.module.css";
import { useEffect, useState } from "react";
import Axios from "Axios";

export default function Home() {
    const [friendAge, setFriendAge] = useState(0);
    const [friendName, setFriendName] = useState("");
    const [listFriend, setListFriend] = useState([]);

    useEffect(() => {
        // READ DATA
        Axios.get("http://localhost:3001/read")
            .then((response) => {
                setListFriend(response.data)
            })
            .catch((error) => {
                console.log(error);
            });
    }, []);

    const addFriend = async () => {
        Axios.post("http://localhost:3001/addFriend", {
            name: friendName,
            age: friendAge,
        });

        setFriendAge("");
        setFriendName("");
    };
    return (
        <div className={css.global_container}>
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className={css.inputs}>
                <input
                    onChange={(e) => {
                        setFriendName(e.target.value);
                    }}
                    placeholder="Friend Name"
                    className={css.input}
                    type="text"
                    value={friendName}
                />
                <input
                    onChange={(e) => {
                        setFriendAge(e.target.value);
                    }}
                    placeholder="Friend Age"
                    className={css.input}
                    type="number"
                    value={friendAge}
                />
                <button onClick={addFriend} className={css.submitButton}>
                    Add friend
                </button>
            </div>

            <div>
                {listFriend.map((value, index) => (
                    <div className={css.friend_card} key={index}>
                        <h1>{value.name}</h1>
                        <p>{value.age} </p>
                    </div>
                ))}
            </div>
        </div>
    );
}
